### ISSUE TITLE
external clock issue

### ISSUE THREAD

**Issue by brettowe** [dorsic/PicoDIV#1]
I recently tried using this with a DS32kHz 32.768khz crystal for the external clock
and I got it to the point where it would turn on the LED but not blink at the expected 1hz

using the internal clock I could get it to blink as expected also could use the DS32 as the external clock sync trigger
to start the blinking so I do think it is at least seeing the clock signal.

is there a lower clock frequency limit with the current code as written?

**Comment by dorsic** [comment]
Hello, the RPi Pico is based on [RP2040](https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf) microcontroller. According to the datasheet, the ref_clk nominal frequency should be in the range 6 MHz - 12 MHz. I have successfully tested it with external clocks between 1 MHz-26 MHz. With such a low frequency chip PIOs may struggle. (Note, the on board LED is driven from the RP2040 internal divider, not from PIO program). The PIO code runs from sys_clk which is directly clocked from external clock. Maybe running it from PLL (as is the case under normal circumstances,  because it runs at 125MHz) will help. But this was not my intention, as this brings additional jitter to the division.

**Comment by brettowe** [comment]
I see.
do you think it could be used just as a sync source?
I'm still unsure on how that part of the program works, is it syncing all the time or just at the start?

**Comment by dorsic** [comment]
Hi, the program uses the PIO of RP2040 to run a simple assembler program that counts the desired amount of instructions (register decrease and jump) and when the register reaches 0 it produces an output signal and starts over. Every instruction takes exactly one clock cycle. The PIO program is clocked by the sys_clk which is set to be driven from the external clock source. 32kHz seems to be just too low clock speed for the chip.
